name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

# Prevent multiple Claude runs on the same issue/PR
concurrency:
  group: claude-${{ github.event.issue.number || github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read

          # Specify model (defaults to Claude Sonnet 4)
          model: "claude-sonnet-4-1-20250805"

          # Set maximum conversation turns to prevent runaway conversations
          max_turns: 10

          # Allow Claude to run Chrome extension development commands
          allowed_tools: |
            Bash(npm install)
            Bash(npm run build)
            Bash(npm run test)
            Bash(npm run lint)
            Bash(npm run typecheck)
            Bash(npm run format:fix)
            Read(packages/**)
            Read(apps/**)
            Read(_docs/**)
            Write
            Edit
            MultiEdit

          # Custom instructions for Chrome extension development
          custom_instructions: |
            You are working on a Chrome Extension (Manifest V3) project called Briefcase.
            Key guidelines:
            - Follow TypeScript best practices
            - Use functional React components with hooks
            - Ensure Chrome Extension security best practices
            - Reference _docs/PRD.md for requirements
            - Check CLAUDE.md for project-specific instructions
            - Use conventional commits format
            - Test changes in Chrome before marking complete

          # Custom environment variables for Claude
          claude_env: |
            NODE_ENV: development
