name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Only run on code changes
    paths:
      - "apps/**/*.ts"
      - "apps/**/*.tsx"
      - "apps/**/*.js"
      - "apps/**/*.jsx"
      - "packages/**/*.ts"
      - "packages/**/*.tsx"
      - "packages/**/*.js"
      - "packages/**/*.jsx"

jobs:
  claude-review:
    # Security: Require manual approval for first-time contributors (GPT-5's recommendation)
    if: |
      github.event.pull_request.author_association != 'FIRST_TIME_CONTRIBUTOR' ||
      github.event.pull_request.author_association != 'FIRST_TIMER'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Changed to write for sticky comments
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Use Claude Sonnet 4.1 for reviews
          model: "claude-sonnet-4-1-20250805"

          # Enable sticky comments to update same comment on subsequent pushes
          use_sticky_comment: true

          # Chrome Extension specific review prompt
          direct_prompt: |
            Please review this Chrome Extension (Manifest V3) pull request focusing on:

            **Chrome Extension Specific:**
            - Manifest permissions are properly declared and justified
            - Content scripts follow security best practices
            - Service worker is properly configured for MV3
            - Side panel functionality works correctly
            - No inline scripts or eval() usage
            - Proper message passing between contexts

            **TypeScript & React:**
            - Type safety and proper interface usage
            - React hooks are used correctly
            - No unnecessary re-renders
            - Component accessibility (ARIA attributes)

            **Security:**
            - No API keys or sensitive data exposed
            - Input validation and sanitization
            - Content Security Policy compliance
            - Safe DOM manipulation

            **Code Quality:**
            - Follows project conventions in CLAUDE.md
            - Uses existing patterns from the codebase
            - Proper error handling
            - Performance considerations

            **Testing:**
            - Test coverage for new features
            - Edge cases are handled

            Be constructive and educational in feedback. Reference specific line numbers when possible.

          # Allow specific tools for testing during review
          allowed_tools: |
            Bash(npm run lint)
            Bash(npm run typecheck)
            Bash(npm run test)
            Read(packages/**)
            Read(apps/**)
            Read(_docs/**)

          # Skip review for WIP or draft PRs
          skip_conditions: |
            contains(github.event.pull_request.title, '[WIP]') ||
            contains(github.event.pull_request.title, '[skip-review]') ||
            github.event.pull_request.draft == true
